# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [73]:
N = 11

# Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))
np.arange(-(N-1), 1) * np.full(N,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [74]:
N=11

# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали
diagarray = np.diag(np.arange(-(N-1), 1, 1), k=0) * np.diag(np.full(N,-1))
print(diagarray)
print(f"Сумма: {diagarray.sum()}")


[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
Сумма: 55


# Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [81]:
from numpy import linalg

# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3
a = np.array( [[4,2,1],
               [1,3,0],
               [0,5,4]] )
b = np.array( [4,12,-3] )

linalg.solve(a, b)

# np.allclose( np.dot(a, linalg.solve(a, b)), b )

array([ 0.46666667,  3.84444444, -5.55555556])

# Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

In [100]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

# Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

# На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

cosine_list = []

for i,vector in enumerate(users_stats):
    vector = users_stats[i]
#     print(vector)
#     print(cosine( vector, next_user_stats ))
    cosine_list.append(cosine( vector, next_user_stats ))
    
similar_user = cosine_list.index(max(cosine_list))

print(f"Самый похожий пользователь - №{similar_user+1}, его история покупок {users_stats[similar_user]} максимально совпадает с историей очередного посетителя {next_user_stats}, косинусное сходство {max(cosine_list)}")


Самый похожий пользователь - №8, его история покупок [0 1 1 0 0 0] максимально совпадает с историей очередного посетителя [0 1 2 0 0 0], косинусное сходство 0.9486832980505138
